Suppress RuboCop offense to fix broken build (#3251)
Follow up to https://github.com/rails/webpacker/pull/3232.

This PR suppresses the following RuboCop offense.

```console
% bundle exec rubocop
(snip)

lib/webpacker/manifest.rb:108:107: C: [Correctable]
Layout/TrailingWhitespace: Trailing whitespace detected.
1. You forgot to install node packages (try `yarn install`) or are
running an incompatible version of Node
                                       ^

64 files inspected, 1 offense detected, 1 offense auto-correctable
Error: Process completed with exit code 1.
```

https://github.com/rails/webpacker/runs/4651343194